package mwk.testmod.common.recipe.base.generator;

public interface GeneratorRecipe {

    /**
     * @return The amount generated by the recipe. Can be energy or temporal flux.
     */
    int getGeneratedAmount();
}
